# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.19.1"

default_platform :ios

platform :ios do
  before_all do
    cocoapods    
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: "GirdersSwift",
      code_coverage: true
    )
  end

  desc "Runs coverage"
  lane :coverage do
    test
    slather(
      travis: true,
      scheme: "GirdersSwift",
      coveralls: true,
      proj: "GirdersSwift.xcodeproj",
      workspace: "GirdersSwift.xcworkspace"
    )
  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
